//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CategoriaGasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriaGasto()
        {
            this.Gasto = new HashSet<Gasto>();
        }

        [Display(Name = "ID")]
        public int idCatGasto { get; set; }
        [StringLength(45, ErrorMessage = "La longitud máxima es de 45 caracteres.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "NombreCategoria")]
        public string nombreCategoria { get; set; }
        [StringLength(45, ErrorMessage = "La longitud máxima es de 45 caracteres.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Descripción")]
        public string descripcion { get; set; }
        [Display(Name = "Estado")]
        public int estado { get; set; } 

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
    }
}
