//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ListaPrecio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListaPrecio()
        {
            this.ListaPrecioDet = new HashSet<ListaPrecioDet>();
        }

        [Display(Name = "ID")]
        public int idListaPrecio { get; set; }    
        public Nullable<int> kermesse { get; set; }
        [StringLength(45, ErrorMessage = "La longitud máxima es de 45 caracteres.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "ListaPrecio")]
        public string nombre { get; set; }
        [StringLength(45, ErrorMessage = "La longitud máxima es de 45 caracteres.")]
        [DataType(DataType.Text, ErrorMessage = "Ingrese un dato de tipo texto.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Descripcion")]
        public string descripcion { get; set; }
        [StringLength(45, ErrorMessage = "La longitud máxima es de 45 caracteres.")]
        [DataType(DataType.Text, ErrorMessage = "Ingrese un dato de tipo texto.")]
        
        [Display(Name = "Estado")]
        public int estado { get; set; }
        [Display(Name = "Kermesse")]
        public virtual Kermesse Kermesse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaPrecioDet> ListaPrecioDet { get; set; }
    }
}
