//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Moneda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Moneda()
        {
            this.ArqueoCajaDet = new HashSet<ArqueoCajaDet>();
            this.Denominacion = new HashSet<Denominacion>();
            this.TasaCambio = new HashSet<TasaCambio>();
            this.TasaCambio1 = new HashSet<TasaCambio>();
        }
    
        public int idMoneda { get; set; }
        [StringLength(45, ErrorMessage = "La longitud máxima es de 45 caracteres.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string nombre { get; set; }
        [StringLength(45, ErrorMessage = "La longitud máxima es de 45 caracteres.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string simbolo { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArqueoCajaDet> ArqueoCajaDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Denominacion> Denominacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasaCambio> TasaCambio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasaCambio> TasaCambio1 { get; set; }
    }
}
