//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Parroquia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parroquia()
        {
            this.Kermesse = new HashSet<Kermesse>();
        }
    
        public int idParroquia { get; set; }
        [StringLength(45, ErrorMessage = "La longitud máxima es de 45 caracteres.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string nombre { get; set; }
        [StringLength(45, ErrorMessage = "La longitud máxima es de 45 caracteres.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string direccion { get; set; }
        [StringLength(45, ErrorMessage = "La longitud máxima es de 45 caracteres.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string telefono { get; set; }
        [StringLength(45, ErrorMessage = "La longitud máxima es de 45 caracteres.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string parroco { get; set; }
        [StringLength(45, ErrorMessage = "La longitud máxima es de 45 caracteres.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string logo { get; set; }
        [StringLength(45, ErrorMessage = "La longitud máxima es de 45 caracteres.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string sitioWeb { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kermesse> Kermesse { get; set; }
    }
}
