//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vw_ArqueoCajaDetalle
    {
        [Display(Name = "Cantidad")]
        public decimal Cantidad { get; set; }
        [Display(Name = "Subtotal")]
        public decimal Subtotal { get; set; }
        [Display(Name = "Kermesse")]
        public string kermesse { get; set; }
        [Display(Name = "Moneda")]
        public string moneda { get; set; }
        [Display(Name = "Valor Letra")]
        public string valorLetra { get; set; }
        [Display(Name = "ID")]
        public int idArqueoCajaDet { get; set; }
    }
}
