//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VW_arqueoCaja
    {
        [Display(Name = "Fecha")]
        public Nullable<System.DateTime> fecha { get; set; }
        [Display(Name = "Total")]
        public Nullable<decimal> total { get; set; }
        [Display(Name = "Creado por")]
        public int CreadoPor { get; set; }
        [Display(Name = "Fecha creación")]
        public System.DateTime fechCr { get; set; }
        [Display(Name = "ID")]
        public int idArqueoCaja { get; set; }
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        [Display(Name = "Usuario")]
        public string userName { get; set; }
    }
}
