//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vw_ArqueoCajaDetalle
    {
        [Display(Name = "Cantidad")]
        [DataType(DataType.Currency, ErrorMessage = "Por favor ingres un dato de tipo decimal")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public decimal Cantidad { get; set; }

        [Display(Name = "Subtotal")]
        [DataType(DataType.Currency, ErrorMessage = "Por favor ingres un dato de tipo decimal")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public decimal Subtotal { get; set; }

        [Display(Name = "Kermesse")]
        [Required(ErrorMessage = "Ingrese un dato válido")]
        public string kermesse { get; set; }

        [Display(Name = "Moneda")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string moneda { get; set; }

        [Display(Name = "")]
        [Required(ErrorMessage = "Ingrese un dato válido")]

        public string valorLetra { get; set; }
        public int idArqueoCajaDet { get; set; }
    }
}
