//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_arqueoCaja
    {
        public int ID { get; set; }
        public string Kermesse { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string Usuario { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
