//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_denominacion
    {
        public int idDenominacion { get; set; }
        public decimal valor { get; set; }
        public string valorLetras { get; set; }
        public int estado { get; set; }
        public string nombre { get; set; }
    }
}
