//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vw_ingresocomunidad
    {
        public int idIngresoComunidad { get; set; }
        [Display(Name = "Kermesse")]
        public string kermesse { get; set; }
        [Display(Name = "Comunidad")]
        public string comunidad { get; set; }
        [Display(Name = "Producto")]
        public string producto { get; set; }
        [Display(Name = "Cantidad de producto")]
        public int cantProducto { get; set; }
        [Display(Name = "Total de bonos")]
        public int totalBonos { get; set; }
        public string usuarioCreacion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string usuarioModificacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public string usuarioEliminacion { get; set; }
        public Nullable<System.DateTime> fechaEliminacion { get; set; }
    }
}
