//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ingresocomunidaddet
    {
        public int idIngresoComunidadDet { get; set; }
        public string ingresoComunidad { get; set; }
        public string bono { get; set; }
        public string denominacion { get; set; }
        public int cantidad { get; set; }
        public double subTotalBono { get; set; }
    }
}
