//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vw_ingresocomunidaddet
    {
        [Display(Name = "ID")]
        public int idIngresoComunidadDet { get; set; }
        [Display(Name = "Ingreso de comunidad")]
        public string ingresoComunidad { get; set; }
        [Display(Name = "Bono")]
        public string bono { get; set; }
        [Display(Name = "Denominación")]
        public string denominacion { get; set; }
        [Display(Name = "Cantidad")]
        public int cantidad { get; set; }
        [Display(Name = "Subtotal")]
        public double subTotalBono { get; set; }
    }
}
