//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vw_kermesse
    {
        public int idKermesse { get; set; }
        [Display(Name = "Parroquia")]
        public string parroquia { get; set; }
        [Display(Name = "Kermesse")]
        public string nombre { get; set; }
        [Display(Name = "Fecha de inicio")]
        public System.DateTime fInicio { get; set; }
        [Display(Name = "Fecha final")]
        public System.DateTime fFinal { get; set; }
        [Display(Name = "Descripción")]
        public string descripcion { get; set; }
        public int estado { get; set; }
        public string usuarioCreacion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string usuarioModificacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public string usuarioEliminacion { get; set; }
        public Nullable<System.DateTime> fechaEliminacion { get; set; }
    }
}
