//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_resumenkermesse
    {
        public int idKermesse { get; set; }
        public string kermesse { get; set; }
        public Nullable<int> ingresos { get; set; }
        public Nullable<double> egresos { get; set; }
    }
}
