//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vw_rolusuario
    {
        [Display(Name = "ID")]
        public int idRolUsuario { get; set; }
        [Display(Name = "Rol")]
        public string rolDescripcion { get; set; }
        [Display(Name = "Estado")]
        public int estado { get; set; }
        [Display(Name = "Nombre")]
        public string nombres { get; set; }
    }
}
