//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_tasacambio
    {
        public int idTasaCambio { get; set; }
        public string monedaO { get; set; }
        public string monedaC { get; set; }
        public string mes { get; set; }
        public int anio { get; set; }
        public int estado { get; set; }
    }
}
