//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vw_tasacambio
    {
        [Display(Name = "ID")]
        public int idTasaCambio { get; set; }
        [Display(Name = "Moneda origen")]
        public string monedaO { get; set; }
        [Display(Name = "Moneda cambio")]
        public string monedaC { get; set; }
        [Display(Name = "Mes")]
        public string mes { get; set; }
        [Display(Name = "Año")]
        public int anio { get; set; }
        [Display(Name = "Estado")]
        public int estado { get; set; }
    }
}
